# Version of Docker-compose
version: '3.8'

services:
    reverseproxy:
        container_name: reverse
        hostname: reverse
        # Creating a custom image
        build:
          # Location to the Dockerfile
          context: ./
          # Name of the Dockerfile
          dockerfile: Dockerfile

        image: nginx
        ports:
            - 443:443
            - 80:80
        restart: always
        volumes:
            - <path/to/your/config>:/nginx
            - <path/to/your/certs>:/front_end/ssl/


    # nginx:
    #     depends_on:
    #         - reverseproxy 
    #         - node
    #     image: nginx:alpine
    #     restart: always
 
    # apache:
    #     depends_on:
    #         - reverseproxy
    #     image: httpd:alpine
    #     restart: always

    # Add node service
    node:
        # Creating a custom image
        build:
            # Location to the Dockerfile
            context: ./back_end
            # Name of the Dockerfile
            dockerfile: Dockerfile
        ports:
            # External port:Internal port
            - 5000:5000
        # ADD THE CONFIGURATION FROM THIS POINT to create a volume named nodeVolume
        volumes:
            # Syntax <nameOfVolume>:<directorInDocker>
            - nodeVolume:/server
            # ADD THE CONFIGURATION FROM THIS POINT to sync the working directory
            # for the application to the /app directory in the container
            - .:/server
            - /server/node_modules

        # ADD THE CONFIGURATION FROM THIS POINT to build the MongoDB service
        environment:
            - PORT=5000
            # For security, specify a username and password as environmental variables
            # Username for the mongo database
            - MONGO_INITDB_ROOT_USERNAME=mern
            # Password for the mongo database
            - MONGO_INITDB_ROOT_PASSWORD=merndocker
    # Enables the mongo service to start before the node service
        depends_on:
            - mongo


    # Add mongoDB service
    mongo:
        # Official mongo image from docker.hub
        image: mongo
        environment:
            # Username for the mongo database
            - MONGO_INITDB_ROOT_USERNAME=mern
            # Password for the mongo database
            - MONGO_INITDB_ROOT_PASSWORD=merndocker
        volumes:
            # <nameOfVolume>:<directorInDocker>
            - mongoDB:/data/db

# Making the volumes accessible by other containers/services
volumes:
  # Declaring the node service volume.
  nodeVolume:
  mongoDB: