# Use a lighter version of Node as a parent image
FROM mhart/alpine-node:8.11.4

# Set the working directory to /front_end
WORKDIR /front_end

# copy package.json into the container at /front_end
COPY package*.json /front_end/

# install dependencies
RUN npm install

# Copy the current directory contents into the container at /front_end
COPY . /front_end/

# Make port 3000 available outside this container
EXPOSE 3000

# Run the app when the container launches
CMD ["npm", "start"]
