const blogData = [
    {
        id: 1,
        title: "Starting My Game Development Journey in Unity",
        date: "2024-01-10",
        summary: "An introduction to my game development adventure — why I chose Unity, what I hope to build, and the skills I'm bringing from software engineering.",
        content: "After years of admiring games as a player and studying computer science, I finally committed to learning Unity seriously. My background in C# and object-oriented design gave me a head start, but game development introduces a whole new set of challenges: physics, rendering pipelines, input systems, and real-time performance constraints. In this post I document the first steps — setting up the project, understanding the scene hierarchy, and writing my first MonoBehaviour scripts. The biggest revelation was how Unity's component-based architecture encourages composition over inheritance, which aligns beautifully with SOLID principles I already follow.",
        tags: ["Unity", "C#", "Beginner"],
        readTime: "4 min read",
    },
    {
        id: 2,
        title: "Applying SOLID Principles to Unity Game Architecture",
        date: "2024-02-03",
        summary: "How the SOLID principles from traditional software engineering translate into Unity game development, with practical examples from my 2D RTS project.",
        content: "One of the biggest mistakes new Unity developers make is cramming all logic into a single MonoBehaviour. In this post I explore how SOLID principles map to Unity architecture. Single Responsibility means separating movement, combat, and UI concerns into dedicated components. Open/Closed Principle encourages using abstract base classes or interfaces so that adding a new unit type doesn't require modifying existing code. Dependency Inversion through ScriptableObject events and interfaces reduces tight coupling between systems. I show concrete examples from my 2D real-time strategy game project where these principles made the codebase significantly easier to extend and debug.",
        tags: ["Unity", "C#", "Architecture", "Design Patterns"],
        readTime: "7 min read",
    },
    {
        id: 3,
        title: "Implementing the Abstract Factory Pattern for Unit Spawning",
        date: "2024-02-20",
        summary: "A deep dive into using the Abstract Factory design pattern to manage the spawning of diverse unit types in a 2D strategy game.",
        content: "When your game has multiple factions, each with their own variants of infantry, cavalry, and siege units, a naive approach quickly leads to bloated switch statements. The Abstract Factory pattern elegantly solves this: define an abstract factory interface with methods like CreateInfantry(), CreateCavalry(), and CreateSiege(). Concrete factories for each faction implement this interface and return faction-specific prefabs. Unity's ScriptableObjects make this especially clean — each faction factory ScriptableObject holds the relevant prefab references. The result is that adding a new faction requires only a new factory ScriptableObject and the prefabs; no existing code needs modification.",
        tags: ["Unity", "C#", "Design Patterns", "Architecture"],
        readTime: "8 min read",
    },
    {
        id: 4,
        title: "Blender Fundamentals: Sculpting a Medieval Sword",
        date: "2024-03-05",
        summary: "A walkthrough of the Blender sculpting and retopology workflow I used to create a game-ready medieval longsword asset.",
        content: "Creating game-ready assets in Blender involves two main phases: sculpting the high-poly mesh to capture all the fine details, and retopology to produce a clean low-poly mesh suitable for a game engine. For this longsword I started with a base cylinder, used Blender's multiresolution modifier for sculpting, and added edge loops to define the blade's fuller and cross-guard geometry. After baking the normal map from the high-poly onto the low-poly, the result looks detailed in Unity without a high polygon count. I also cover UV unwrapping, the importance of clean seams for texturing, and exporting the FBX for Unity import.",
        tags: ["Blender", "3D Modelling", "Asset Creation"],
        readTime: "6 min read",
    },
    {
        id: 5,
        title: "Understanding Unity's Physics System for RTS Unit Movement",
        date: "2024-03-22",
        summary: "Exploring Rigidbody2D versus direct Transform manipulation for unit movement in a 2D RTS, and the performance trade-offs of each approach.",
        content: "Movement in a 2D RTS game seems straightforward until units start colliding, stacking, and clipping through walls. This post compares using Rigidbody2D with forces versus directly manipulating Transform.position. Rigidbody2D is physics-aware and handles collisions naturally, but requires careful use of FixedUpdate and can introduce jitter when forces are applied per frame. Transform-based movement is more predictable and easier to debug, but you must manually handle obstacle avoidance. I settled on a hybrid: Rigidbody2D for collision resolution with kinematic mode and manually computed velocity. I also discuss NavMesh2D as an alternative for complex pathfinding scenarios.",
        tags: ["Unity", "C#", "Physics", "Game Design"],
        readTime: "6 min read",
    },
    {
        id: 6,
        title: "Implementing the Mediator Pattern for UI and Game System Decoupling",
        date: "2024-04-08",
        summary: "How I used the Mediator pattern combined with ScriptableObject events to keep the UI layer completely decoupled from core game systems.",
        content: "A common trap in Unity projects is having UI scripts directly reference game managers, creating a web of dependencies. The Mediator pattern addresses this by introducing an intermediary that coordinates communication. In my setup, ScriptableObjects act as event channels: a GameEvent ScriptableObject holds a list of listeners and a Raise() method. UI components and game systems both reference these event channels rather than each other directly. When a unit is selected, the SelectionManager raises a UnitSelectedEvent. The UI script listens to this event and updates without knowing anything about the SelectionManager. This approach makes the UI completely reusable and testable in isolation.",
        tags: ["Unity", "C#", "Design Patterns", "Architecture"],
        readTime: "7 min read",
    },
    {
        id: 7,
        title: "Texture Painting in Blender: Bringing Characters to Life",
        date: "2024-04-25",
        summary: "My workflow for hand-painting character textures in Blender's texture paint mode, including tips for stylised game art.",
        content: "Procedural textures are powerful but for a stylised 2D-feel in a 3D game, hand-painted textures often look better. Blender's texture paint mode lets you paint directly onto the 3D mesh, seeing the result on the model in real time. I cover setting up the workspace with multiple views (3D viewport, UV editor, and image editor open simultaneously), choosing the right brush types (fill, draw, soften), and layering base colours before adding shadows and highlights. For game art, keeping the texture resolution at 512×512 or 1024×1024 and using a limited colour palette helps maintain a cohesive visual style and keeps memory usage low.",
        tags: ["Blender", "3D Modelling", "Asset Creation", "Art"],
        readTime: "5 min read",
    },
    {
        id: 8,
        title: "Story Design: Building a Fictional World for Our 2D RTS",
        date: "2024-05-12",
        summary: "Insights into the collaborative world-building process — how my partner and I created the narrative, factions, and lore for our ongoing game project.",
        content: "Great mechanics alone don't make a memorable game — story and world-building create the emotional investment that keeps players engaged. My partner and I spent months developing a fictional world inspired by the conflicts of the Bronze Age Collapse. We defined three distinct factions, each with unique motivations, aesthetics, and unit rosters that reflect their culture. We wrote a 20,000-word lore document covering history, geography, religion, and key figures. In Unity, we translate this lore into level design, dialogue, and mission objectives. This post discusses the tools we use (collaborative markdown docs and Obsidian for note-linking), how lore decisions influenced gameplay mechanics, and keeping narrative consistent across a long development cycle.",
        tags: ["Game Design", "Narrative", "World Building"],
        readTime: "9 min read",
    },
];

export default blogData;
